### PR TITLE
Mailing Script

### PR DESCRIPTION
**Pull request by pragatipal**

### CODE REVIEW

**Comment by pragatipal** [comment]
Please merge my PR.

**Comment by dscgecbsp** [comment]
add a comment at the top to define problem statement 
and add a image which shows working of this code

**Comment by juhi0103** [comment]
> add a comment at the top to define problem statement and add a image which shows working of this code

Please remove the spam label, this is not letting me participate for hacktoberfest this year.

**Comment by juhi0103** [comment]
> add a comment at the top to define problem statement and add a image which shows working of this code

Please remove the label now atleast. So that I can participate in Hacktoberfest this year.

**Pull request closed without merging**
