### PR TITLE
Added a CPP program to implement Binary Search 

### PR DESCRIPTION
**Pull request by SHARMA-SAURAV**
Added a CPP program to implement Binary Search

### CODE REVIEW

**Comment by dscgecbsp** [comment]
already present in this repo

**Comment by SHARMA-SAURAV** [comment]
This time i was added a linked_list program so why you clased

**Comment by SHARMA-SAURAV** [comment]
Closed*

**Comment by SHARMA-SAURAV** [comment]
Please give "hacktoberfest accepted" label to it.

**Pull request closed without merging**
